services:
  api:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
      args:
        PIP_EXTRAS: "dev,metrics,tracing"
    container_name: prodkit-api
    working_dir: /workspace
    volumes:
      - .:/workspace:delegated
      - prodkit_venv:/opt/venv
    environment:
      #optionnal
      PROD_ENV: "dev"
      SERVICE_NAME: "prodkit-example"

      # OTel (tracing profile)
      OTEL_SERVICE_NAME: "prodkit-example"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
      OTEL_TRACES_EXPORTER: "otlp"
      OTEL_METRICS_EXPORTER: "none"
      OTEL_LOGS_EXPORTER: "none"
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/healthz').read()\""]
      interval: 10s
      timeout: 3s
      retries: 10
    profiles: ["core"]

  # -------------------------
  # Metrics (optional)
  # -------------------------
  prometheus:
    image: prom/prometheus:latest
    container_name: prodkit-prometheus
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - api
    profiles: ["metrics"]

  grafana:
    image: grafana/grafana:latest
    container_name: prodkit-grafana
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    profiles: ["metrics"]

  # -------------------------
  # Tracing (optional)
  # -------------------------
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: prodkit-otel-collector
    command: ["--config=/etc/otelcol-contrib/config.yml"]
    volumes:
      - ./docker/otel/otel-collector.yml:/etc/otelcol-contrib/config.yml:ro
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    profiles: ["tracing"]

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: prodkit-jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686" # UI
      - "14250:14250" # collector gRPC
    profiles: ["tracing"]

volumes:
  prodkit_venv:
  grafana_data: